service_department/pm_form_project/pm_form_project/urls.py
from django.contrib import admin
from django.urls import path
from pm_form_app.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
]

service_department/pm_form_project/pm_form_app/models.py
from django.db import models

# Create your models here.
class FormData(models.Model):
    model = models.CharField(max_length=100)
    sn = models.CharField(max_length=20)
    temperature = models.IntegerField()

service_department/pm_form_project/pm_form_app/forms.py
from django import forms
from .models import FormData
class FormDataForm(forms.ModelForm):
    class Meta:
        model = FormData
        fields = ['model', 'sn', 'temperature']


service_department/pm_form_project/pm_form_app/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .forms import FormDataForm
def index(request):
    if request.method == 'POST':
        form = FormDataForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')  # Redirect after form submission
    else:
        form = FormDataForm()
    return render(request, 'form_app/form.html', {'form': form})


service_department/pm_form_project/pm_form_app/templates/form_app/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fillable Form</title>
</head>
<body>
    <h1>Instrument Log</h1>
<form method="POST">
    {% csrf_token %}
    <!-- The table tags below allows for the fields be lined up vertically. -->
    <table>
        <tr>
            <td><label for="id_model">Model:</label></td>
            <td>{{ form.model }}</td>
        </tr>
        <tr>
            <td><label for="id_sn">SN:</label></td>
            <td>{{ form.sn }}</td>
        </tr>
        <tr>
            <td><label for="id_temperature">Temperature:</label></td>
            <td>{{ form.temperature }}</td>
        </tr>
    </table>
    <button type="submit">Submit</button>
</form>

</body>
</html>